use_frameworks!

platform :ios, '9.0'

target 'XDBusinessModule_Example' do
  pod 'XDBusinessModule', :path => '../'

  target 'XDBusinessModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
